# print("Hello")
# print("Name : ","Nisha")
# print("Age : ",20)
# print("Course : ","B.Tech in CSE")
# print("Goal : ","Data Analyst")

# print("I am learning Python.")
# print("Python will help me in Data Analytics.")
# print("I want to learn AI and Machine Learning.")

print("===============================")
print("          MY PROFILE")
print("===============================")
print("Name : ","Nisha")
print("Course : ","B.Tech in CSE")
print("Interest : ","Data Analytics")
print("Language : ","Python")
print("===============================")